// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCollection.Models;

namespace MovieCollection.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    partial class MovieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieCollection.Models.MovieForm", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action",
                            Director = "Jon Watts",
                            Edited = false,
                            Lent = " ",
                            Notes = "Love this show so much!",
                            Rating = "PG-13",
                            Title = "Spider Man No Way Home",
                            Year = 2021
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Romantic Comedy",
                            Director = "Andy Tennant",
                            Edited = false,
                            Lent = " ",
                            Notes = "Love this show so much!",
                            Rating = "PG-13",
                            Title = "Hitch",
                            Year = 2005
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Drama/Musical",
                            Director = "Jon M. Chu",
                            Edited = false,
                            Lent = " ",
                            Notes = "Love this show so much!",
                            Rating = "PG-13",
                            Title = "In the Heights",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
